dress-Shop/Areas/Admin/Controllers/CompanyController.cs
using DressShop.DataAccess.Data;
using DressShop.DataAccess.Repository.IRepository;
using DressShop.Models;
using DressShop.Models.ViewModels;
using DressShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using static System.Net.Mime.MediaTypeNames;


namespace dress_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
       
        public IActionResult Index()
        {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
            return View(objCompanyList);
        }

        public IActionResult Upsert(int? id)
        {
            if (id == null || id == 0)
            {
                //create
                return View(new Company());
            }
            else
            {
                //update
                Company companyObj = _unitOfWork.Company.Get(u => u.Id == id);
                return View(companyObj);
            }
        }


        [HttpPost]
        public IActionResult Upsert(Company CompanyObj)
        {
            if (ModelState.IsValid)
            {
                if (CompanyObj.Id == 0)
                {
                    _unitOfWork.Company.Add(CompanyObj);
                }
                else 
                {
                    _unitOfWork.Company.Update(CompanyObj);
                }
                _unitOfWork.Save();
                TempData["success"] = "Company created successfully";
                return RedirectToAction("Index");
            }
            else 
            {
                return View(CompanyObj  );
            }
         

        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
            return Json(new { data = objCompanyList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var CompanyToBeDeleted = _unitOfWork.Company.Get(u => u.Id==id);
            if (CompanyToBeDeleted == null) 
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Company.Remove(CompanyToBeDeleted);
            _unitOfWork.Save();
            
            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

dress-Shop/Areas/Admin/Views/Company/Index.cshtml
    <div class="container">
        <div class="row pt-4 pb-3">
            <div class="col-6">
                <h2 class="text-primary">Company List</h2>
            </div>
        <div class="col-6 text-end">
            <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Create New Company
            </a>
        </div>

        </div>

<table id="tblData" class="table table-bordered table-striped" style="width:100%">
    <thead>
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Phone Number</th>
        <th></th>
    </tr>
    </thead>
   
</table>

</div>
@section Scripts {
    <script src="~/js/company.js"></script>
}

dress-Shop/Areas/Admin/Views/Company/Upsert.cshtml
@model Company


<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id == 0 ? "Create" : "Update") Company</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row" >
                <div class="col-12 ">
                    <div class="border p-3">
                        @*<div asp-validation-summery="ModelOnly"></div >*@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PhoneNumber" class="form-control border-0 shadow" />
                            <label asp-for="PhoneNumber" class="ms-2"></label>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="StreetAddress" class="form-control border-0 shadow" />
                            <label asp-for="StreetAddress" class="ms-2"></label>
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" class="form-control border-0 shadow" />
                            <label asp-for="City" class="ms-2"></label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" class="form-control border-0 shadow" />
                            <label asp-for="State" class="ms-2"></label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PostalCode" class="form-control border-0 shadow" />
                            <label asp-for="PostalCode" class="ms-2"></label>
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>

                        <div class="row">
                            <div class="col-6 col-md-3">
                                @if (Model.Id == 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                    
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }

                            </div>

                            <div class="col-6 col-md-3">
                                <a asp-controller="Company" class="btn btn-outline-primary border form-control" asp-action="Index">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           
        </form>
    </div>
</div>



@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}