dress-Shop/Areas/Admin/Controllers/ProductController.cs
using DressShop.DataAccess.Data;
using DressShop.DataAccess.Repository.IRepository;
using DressShop.Models;
using DressShop.Models.ViewModels;
using DressShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using static System.Net.Mime.MediaTypeNames;



namespace dress_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties:"Category").ToList();
            return View(objProductList);
        }
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Product = new Product()
            };
            if (id == null || id == 0)
            {
                //create
                return View(productVM);
            }
            else
            {
                //update
                productVM.Product = _unitOfWork.Product.Get(u => u.Id == id);
                return View(productVM);
            }
        }
        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                { 
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images\product");

                    if (!string.IsNullOrEmpty(productVM.Product.ImageUrl)) 
                    {
                        //delete the old image
                        var oldImagePath =
                            Path.Combine(wwwRootPath, productVM.Product.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath)) 
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    { 
                        file.CopyTo(fileStream);
                    }
                    productVM.Product.ImageUrl = @"\images\product\" + fileName; 
                }

                if (productVM.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productVM.Product);
                }
                else 
                {
                    _unitOfWork.Product.Update(productVM.Product);
                }
                _unitOfWork.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            else 
            {
                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                return View(productVM);
            }
         

        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = objProductList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork.Product.Get(u => u.Id==id);
            if (productToBeDeleted == null) 
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            var oldImagePath =  
                           Path.Combine(_webHostEnvironment.WebRootPath, 
                           productToBeDeleted.ImageUrl.TrimStart('\\'));

            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.Product.Remove(productToBeDeleted);
            _unitOfWork.Save();
            
            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

dress-Shop/Areas/Admin/Views/Product/Create.cshtml
@model ProductVM


<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Product.Title" class="form-control border-0 shadow"  />
                    <label asp-for="Product.Title" class="ms-2"></label>
                    <span asp-validation-for="Product.Title" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Product.Description" class="form-control border-0 shadow" />
                    <label asp-for="Product.Description" class="ms-2"></label>
                    <span asp-validation-for="Product.Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Product.ListPrice" class="form-control border-0 shadow" />
                    <label asp-for="Product.ListPrice" class="ms-2"></label>
                    <span asp-validation-for="Product.ListPrice" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Product.Price" class="form-control border-0 shadow" />
                    <label asp-for="Product.Price" class="ms-2"></label>
                    <span asp-validation-for="Product.Price" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Product.Price50" class="form-control border-0 shadow" />
                    <label asp-for="Product.Price50" class="ms-2"></label>
                    <span asp-validation-for="Product.Price50" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Product.Price100" class="form-control border-0 shadow" />
                    <label asp-for="Product.Price100" class="ms-2"></label>
                    <span asp-validation-for="Product.Price100" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <select asp-for="@Model.Product.CategoryId" asp-items="@Model.CategoryList" class="form-select border-0 shadow">
                        <option disabled selected>--Select Category--</option>
                    </select>
                    <label asp-for="Product.CategoryId" class="ms-2"></label>
                    <span asp-validation-for="Product.CategoryId" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Product.ImageUrl" class="form-control border-0 shadow" />
                    <label asp-for="Product.ImageUrl" class="ms-2"></label>
                    <span asp-validation-for="Product.ImageUrl" class="text-danger"></span>
                </div>
             
                <div class="row">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Create</button>
                    </div>

                    <div class="col-6 col-md-3">
                        <a class="btn btn-outline-primary border form-control" asp-controller="Product" asp-action="Index">
                            Back to List
                        </a>
                    </div>
                </div>


            </div>
        </form>
    </div>
</div>



@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

dress-Shop/Areas/Admin/Views/Product/Index.cshtml
@model List<Product>


    <div class="container">
        <div class="row pt-4 pb-3">
            <div class="col-6">
                <h2 class="text-primary">
                    Product List
                </h2>
            </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Create New Product
            </a>
        </div>

        </div>

<table id="tblData" class="table table-bordered table-striped" style="width:100%">
    <thead>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>ListPrice</th>
        <th>Category</th>
        <th></th>
    </tr>
    </thead>
   
</table>

</div>
@section Scripts{
    <script src="~/js/product.js"></script>
}

dress-Shop/Areas/Admin/Views/Product/Upsert.cshtml
@model ProductVM


<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Product.Id == 0 ? "Create" : "Update") Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Product.Id" hidden />
            <input asp-for="Product.ImageUrl" hidden />
            <div class="row" >
                <div class="col-10">
                    <div class="border p-3">
                        @*<div asp-validation-summery="ModelOnly"></div >*@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Product.Title" class="form-control border-0 shadow" />
                            <label asp-for="Product.Title" class="ms-2"></label>
                            <span asp-validation-for="Product.Title" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Product.Description" class="form-control border-0 shadow" />
                            <label asp-for="Product.Description" class="ms-2"></label>
                            <span asp-validation-for="Product.Description" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Product.ListPrice" class="form-control border-0 shadow" />
                            <label asp-for="Product.ListPrice" class="ms-2"></label>
                            <span asp-validation-for="Product.ListPrice" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Product.Price" class="form-control border-0 shadow" />
                            <label asp-for="Product.Price" class="ms-2"></label>
                            <span asp-validation-for="Product.Price" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Product.Price50" class="form-control border-0 shadow" />
                            <label asp-for="Product.Price50" class="ms-2"></label>
                            <span asp-validation-for="Product.Price50" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Product.Price100" class="form-control border-0 shadow" />
                            <label asp-for="Product.Price100" class="ms-2"></label>
                            <span asp-validation-for="Product.Price100" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <select asp-for="@Model.Product.CategoryId" asp-items="@Model.CategoryList" class="form-select border-0 shadow">
                                <option disabled selected>--Select Category--</option>
                            </select>
                            <label asp-for="Product.CategoryId" class="ms-2"></label>
                            <span asp-validation-for="Product.CategoryId" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input type="file" name="file" class="form-control border-0 shadow" />
                            <label asp-for="Product.ImageUrl" class="ms-2"></label>
                        </div>

                        <div class="row">
                            <div class="col-6 col-md-3">
                                @if (Model.Product.Id == 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                    
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }

                            </div>

                            <div class="col-6 col-md-3">
                                <a class="btn btn-outline-primary border form-control" asp-controller="Product" asp-action="Index">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <img src="@Model.Product.ImageUrl" width="100%"
                    style="border-radius:5px; border:1px solid #bbb9b9" />
                </div>
            </div>
           
        </form>
    </div>
</div>



@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}